blog_lav/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();


Route::get('/', 'PostController@index')->name('post.index');
Route::resource('posts', 'PostController');
Route::resource('comentarios', 'ComentarioController');

blog_lav/app/Comentario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comentario extends Model
{
	protected $fillable = [
		'comentario'
	];

	public $timestamps = false;
}

blog_lav/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	protected $fillable = [
		'titulo',
		'conteudo'
	];

	public $timestamps = false;
}

blog_lav/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

blog_lav/app/Http/Controllers/ComentarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Comentario;

class ComentarioController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
	    $request->validate([
		    'comentario' => 'required|max:500'
	    ]);

	    $comentario = new Comentario();
	    $comentario['comentario'] = $request->get('comentario');
	    $comentario['post'] = $request->get('post_id');
	    $comentario['data_comentario'] = Carbon::now();
	    $comentario->save();

	    return redirect()->back()->with('Sucesso', 'Comentario criado, obrigado pela contribuição :)');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
	    Comentario::where('comentario_id', $id)->delete();
	    return redirect()->back()->with('Sucesso', 'Comentario deletado :(');
    }
}

blog_lav/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

blog_lav/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

blog_lav/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use Auth;
use Carbon\Carbon;
use App\Comentario;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $posts = Post::orderBy('data_postagem', 'desc')->paginate(5);

	    return view('posts.index', compact('posts'))
		    ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
	    if (!Auth::check())
	    {
		    return redirect()->route('login');
	    }

	    return view('posts.criar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
            if (!Auth::check())
	    {
		    return redirect()->route('login');
	    }
	    
	    $request->validate([
		    'titulo' => 'required|max:70',
		    'conteudo' => 'required'
	    ]);
	    $post = new Post();
	    $post['titulo'] = $request->get('titulo');
	    $post['conteudo'] = $request->get('conteudo');
	    $post['autor'] = Auth::id();
	    $post['data_postagem'] = Carbon::now();
	    
	    $post->save();

	    return redirect()->route('posts.index')->with('Sucesso', 'Post criado :)');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
	    $post = Post::find($id);
	    $comentarios = Comentario::where('post', $id)->orderBy('data_comentario', 'desc')->get();
	    return view('posts.mostrar')
		    ->with('post', $post)
	    	    ->with('comentarios', $comentarios);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
	    if (!Auth::check())
	    {
		    return redirect()->route('login');
	    }

	    $post = Post::find($id);
	    return view('posts.editar', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
	    if (!Auth::check())
	    {
		    return redirect()->route('login');
	    }            

            $request->validate([
		    'titulo' => 'required|max:70',
		    'conteudo' => 'required'
	    ]);

	    Post::find($id)->update($request->all());

	    return redirect()->route('posts.index')->with('Sucesso', 'Post atualizado :)');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
	    if (!Auth::check())
	    {
		    return redirect()->route('login');
	    }

	    Post::find($id)->delete();
	    return redirect()->route('posts.index')->with('Sucesso', 'Post deletado :(');
    }
}

blog_lav/resources/views/layout.blade.php
<!doctype html>
<html>
	<head>
		<title>
			Simple Blog - o simples blog
		</title>
		<link rel="stylesheet" href="{{asset('css/app.css')}}">
		<link rel="stylesheet" href="{{asset('css/custom.css')}}">
	</head>
	<body>
	<nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Simple Blog - o simples blog') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Logar</a></li>
                            <li><a href="{{ route('register') }}">Registrar</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>	
		<div class="container">
			@yield('content')
		</div>
		<footer class="page-footer font-small black">
			<div class="footer-copyright text-center py-3">
				<span>
					2019 &#169; | Simple Blog - o simples blog &#8482;
				</span>
			</div>
		</footer>
		<script src="{{ asset('js/app.js') }}"></script>
	</body>
</html>

blog_lav/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

blog_lav/resources/views/posts/criar.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Postar publicação</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}">Voltar</a>
            </div>
        </div>
    </div>


    @if (count($errors) < 0)
        <div class="alert alert-danger">
            <span><strong>Opa!</strong> Tem algo errado!!!</span><br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
	
    <form class="" method="POST" action="{{route('posts.store')}}">
         @include('posts.form')
    </form>


@endsection

blog_lav/resources/views/posts/editar.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar post</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}"> Voltar</a>
            </div>
        </div>
    </div>


    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <span><strong>Opa!</strong> tem algo errado!!!</span><br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    
    <form method="POST" action="{{route('posts.update', $post->id)}}">
	{{ method_field('PATCH') }}  
        @include('posts.form')
    </form>
@endsection

blog_lav/resources/views/posts/form.blade.php
{{csrf_field()}}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
	    <strong>Título:</strong>
	    <input type="text" class="form-control" placeholder="Título" id="titulo" name="titulo" value="@isset($post->titulo){{$post->titulo}}@endisset">
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
	    <strong>Conteúdo:</strong>
	    <textarea class="form-control" id="conteudo" name="conteudo" placeholder="Digite o conteúdo" style="height:300px">@isset($post->conteudo){{$post->conteudo}}@endisset</textarea>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Publicar</button>
    </div>
</div>

blog_lav/resources/views/posts/index.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
	    <div class="pull-left">
		@auth
		<h2>Todas as publicações</h2>
		@endauth
		@guest
		<h2>Publicações<h2>
		@endguest
	    </div>
	    @auth
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('posts.create') }}">Criar novo post</a>
	    </div>
	    @endauth

        </div>
    </div>


    @if ($message = Session::get('Sucesso'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
	<tr>
	    @auth
	    <th>Id</th>
	    @endauth
            <th>Título</th>
            <th>Data de postagem</th>
            <th width="280px"></th>
        </tr>
    @foreach ($posts as $post)
    <tr>
        @auth
	<td>{{ $post->id }}</td>
	@endauth
        <td>{{ $post->titulo}}</td>
        <td>{{ $post->data_postagem}}</td>
        <td>
	    <a class="btn btn-info" href="{{ route('posts.show',$post->id) }}">Visualizar</a>
	    @auth
	    <a class="btn btn-primary" href="{{ route('posts.edit',$post->id) }}">Editar</a>

	    <form method="post" action="{{route('posts.destroy', $post->id)}}" style="display:inline">
		{{csrf_field()}}
		{{ method_field('DELETE') }} 
	    	<input type="submit" class="btn btn-danger" value="Deletar" onclick="return confirm('Deseja mesmo deletar esse post?')">
	    </form>
	    @endauth
        </td>
    </tr>
    @endforeach
    </table>
{!!$posts->links()!!}

@endsection

blog_lav/resources/views/posts/mostrar.blade.php
@extends('layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('posts.index') }}"> Voltar</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <h1>{{ $post->titulo}}</h1>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
	    <div class="form-group">
                <pre style="background-color: white;white-space:pre-wrap;">{{ $post->conteudo}}</pre>
            </div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12 text-right">
            <div class="form-group">
                <strong>Data da postagem:</strong>
                {{ $post->data_postagem}}
            </div>
	</div>
	<br>

	<div class="col-xs-12 col-sm-12 col-md-12">
	    @if ($message = Session::get('Sucesso'))
            <div class="alert alert-success">
           	<p>{{ $message }}</p>
            </div>
            @endif
            <div class="form-group">
		<h3><strong>Comentarios:</strong><h3>
			<div class="widget-area no-padding blank" style="margin-bottom: 40px">
				<div class="status-upload">
						<form action="{{route('comentarios.store')}}" method="POST">
							{{csrf_field()}}
							<input type="hidden" value="{{$post->id}}" name="post_id">
							<textarea placeholder="Qual a sua opnião? Nos conte!" name="comentario" ></textarea>
							<button type="submit" class="btn btn-success green form-control"><i class="fa fa-share"></i>Comentar!</button>
						</form>
					</div>
				</div>
			</div>
		@foreach ($comentarios as $comentario)
		<div class="container">
			<div class="col-sm-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<strong>Visitante</strong> <span class="text-muted">Comentado em: {{$comentario->data_comentario}}</span>
						@auth
						<form method="post" action="{{route('comentarios.destroy', $comentario->comentario_id)}}" style="display:inline;">
							{{csrf_field()}}
							{{ method_field('DELETE') }}
							<span class="text-right clearfix"><input type="submit" class="btn btn-danger clearfix" value="Apagar" style="float:right;" onclick="return confirm('Deseja mesmo deletar esse comentario?')"></span>
						</form>
						@endauth
					</div>
					<div class="panel-body">
						<pre style="background-color: transparent; border: 0px">{{$comentario->comentario}}</pre>
					</div>
				</div>
			</div>
	       </div>	
		@endforeach
            </div>
	</div>
    </div>
@endsection

blog_lav/resources/views/posts/principal.blade.php
@extends('layout')

@section('content')

<div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Posts</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('/') }}"> Voltar</a>
            </div>
        </div>
    </div>


    <div class="row">
	@foreach($posts as $post)
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Título:</strong>
                {{ $post->titulo}}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Conteúdo:</strong>
                {{ $post->conteudo}}
            </div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Data da postagem:</strong>
                {{ $post->data_postagem}}
            </div>
	</div>
	@endforeach
    </div>

@endsection